ALTER TABLE items ADD COLUMN user_id UUID NOT NULL;

ALTER TABLE folders ADD COLUMN user_id UUID NOT NULL;

ALTER TABLE items ADD CONSTRAINT fk_items_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE folders ADD CONSTRAINT fk_folders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;